name: quantum-experiments
dependencies:
  - jupyter=1.0.*
  - pip=20.1.*
  - seaborn=0.10.*
  - pip:
    - qiskit==0.29.*
    - pylatexenc==2.10
    - git+https://github.com/qiskit-community/qiskit-textbook.git#subdirectory=qiskit-textbook-src
